### ISSUE TITLE
if scroll >0, hovering over sun/moon resets scroll

### ISSUE THREAD

**Issue by jkao1** [jkao1/jkao1.github.io#1]
Note that the sun/moon is the yellow circle which hides most elements on the page when you hover over it.

I am using jQuery `show()`/`hide()` to implement this hovering. However, because I am hiding every element and then showing it again, the scroll resets, leading to a glitch-y scroll-to-top whenever I mouseover/mouseleave the sun/moon while my scroll > 0. Is there any way to somehow preserve height to make sure that this glitch does not happen?

**Comment by abdulsamad234** [comment]
I'll like to help fix this bug

**Comment by abdulsamad234** [comment]
I have fixed it
i'll make a pull request now
